// Gameplay tuning data: roles, weapons, guided munitions and enemy unit stats.

// threat: 'yellow' = can be COUNTERED with the counter button at the right moment.
//         'red'    = cannot be countered; you must physically evade (break turn / move out).
export const MISSILES = {
  aam: { name: 'AAM', model: 'small', speed: 105, boost: 145, turn: 2.3, ctrlTurn: 1.9, fuel: 13, fuse: 2.6, splash: 5,
    dmg: { air: 130, ground: 45, naval: 25, static: 30, missile: 100 }, threat: 'yellow', flareable: true, trail: 0xd8d8d4 },
  agm: { name: 'AGM', model: 'small', speed: 72, boost: 110, turn: 1.4, ctrlTurn: 1.35, fuel: 22, fuse: 1.6, splash: 8,
    dmg: { air: 60, ground: 230, naval: 260, static: 260 }, threat: 'yellow', trail: 0xd0ccc4 },
  atgm: { name: 'ATGM', model: 'small', speed: 44, boost: 66, turn: 1.6, ctrlTurn: 1.45, fuel: 26, fuse: 1.4, splash: 5,
    dmg: { air: 90, ground: 190, naval: 130, static: 160 }, threat: 'yellow', trail: 0xd6d3cc },
  cruise: { name: 'CRUISE', model: 'big', speed: 60, boost: 96, turn: 1.05, ctrlTurn: 1.05, fuel: 110, fuse: 2.2, splash: 22,
    dmg: { air: 200, ground: 480, naval: 650, static: 650 }, threat: 'yellow', trail: 0xcac6be, hp: 25 },
  sam: { name: 'SAM', model: 'small', speed: 112, boost: 150, turn: 2.5, ctrlTurn: 2.1, fuel: 15, fuse: 4, splash: 6,
    dmg: { air: 170, ground: 40, naval: 30, static: 30, missile: 200 }, threat: 'yellow', trail: 0xe0dfdb },
  gbomb: { name: 'GLIDE BOMB', model: 'bomb', unpowered: true, speed: 0, turn: 0.9, ctrlTurn: 0.85, fuel: 60, fuse: 1.8, splash: 17,
    dmg: { air: 100, ground: 320, naval: 380, static: 420 }, threat: 'yellow' },
  // hostile
  e_ir: { name: 'IR missile', model: 'small', speed: 96, turn: 1.9, fuel: 9, fuse: 2.6, splash: 4, dmg: { air: 38, ground: 20, naval: 20, missile: 60 },
    threat: 'yellow', flareable: true, trail: 0xd8d8d4 },
  e_radar: { name: 'Radar SAM', model: 'small', speed: 100, turn: 1.05, fuel: 14, fuse: 3.2, splash: 6, dmg: { air: 55, ground: 25, naval: 25, missile: 80 },
    threat: 'red', losLock: true, trail: 0xe7e2d8 },
  e_atgm: { name: 'ATGM', model: 'small', speed: 40, turn: 1.4, fuel: 18, fuse: 1.5, splash: 4, dmg: { ground: 60, naval: 40, air: 40, static: 40 },
    threat: 'yellow', flareable: true, trail: 0xd6d3cc },
  e_ashm: { name: 'Anti-ship missile', model: 'big', speed: 62, turn: 1.0, fuel: 45, fuse: 2.5, splash: 8, dmg: { naval: 120, ground: 60 },
    threat: 'yellow', flareable: true, seaSkim: true, trail: 0xcac6be, hp: 10 },
  e_torp: { name: 'Torpedo', model: 'torpedo', speed: 19, turn: 0, fuel: 40, fuse: 2.5, splash: 6, dmg: { naval: 170 },
    threat: 'red', torpedo: true },
};

export const ROLES = {
  jet: {
    name: 'Fighter Jet', short: 'JET', type: 'plane', model: 'jet', hp: 100,
    desc: 'Fast multirole fighter. Dogfights, interceptions and precision strikes.',
    minSpeed: 24, cruise: 46, maxSpeed: 88, pitchRate: 1.55, rollRate: 3.1, yawRate: 0.55, stall: 20,
    primary: { kind: 'gun', name: 'GUN', rate: 16, speed: 430, dmg: { air: 7, ground: 2.5, naval: 1.5, static: 2, missile: 6 }, spread: 0.004, heatPer: 0.012 },
    secondaries: [{ spec: 'aam', ammo: 16 }, { spec: 'agm', ammo: 6 }],
    counter: { name: 'FLARES', cd: 2.6 },
    stats: { Speed: 5, Armor: 2, Firepower: 3, Agility: 5 },
    camDist: 7.5, camHeight: 1.6,
  },
  striker: {
    name: 'Attack Plane', short: 'ATK', type: 'plane', model: 'striker', hp: 190,
    desc: 'Armoured ground-attack aircraft. Glide bombs, heavy cannon and rockets.',
    minSpeed: 18, cruise: 32, maxSpeed: 56, pitchRate: 1.25, rollRate: 2.2, yawRate: 0.5, stall: 15,
    primary: { kind: 'gun', name: 'CANNON', rate: 10, speed: 370, dmg: { air: 9, ground: 14, naval: 6, static: 9, missile: 8 }, spread: 0.006, heavy: true, heatPer: 0.016 },
    secondaries: [{ spec: 'gbomb', ammo: 8 }, { spec: 'agm', ammo: 6 }, { rocket: true, name: 'ROCKETS', ammo: 40 }],
    counter: { name: 'FLARES', cd: 2.6 },
    stats: { Speed: 3, Armor: 4, Firepower: 5, Agility: 3 },
    camDist: 8, camHeight: 1.8,
  },
  heli: {
    name: 'Gunship Helicopter', short: 'HELO', type: 'heli', model: 'heli', hp: 130,
    desc: 'Hover, hide behind hills and hunt armour with steerable ATGMs.',
    maxSpeed: 30, climb: 14,
    primary: { kind: 'gun', name: 'CHAIN GUN', rate: 9, speed: 320, dmg: { air: 7, ground: 9, naval: 4, static: 5, missile: 6 }, spread: 0.008, heavy: true, heatPer: 0.014 },
    secondaries: [{ spec: 'atgm', ammo: 8 }, { rocket: true, name: 'ROCKETS', ammo: 38 }],
    counter: { name: 'FLARES', cd: 2.6 },
    stats: { Speed: 2, Armor: 3, Firepower: 4, Agility: 4 },
    camDist: 10, camHeight: 3,
  },
  tank: {
    name: 'Main Battle Tank', short: 'TANK', type: 'ground', model: 'tank', hp: 330,
    desc: 'Heavy armour. Ballistic cannon with auto-ranging and a guided ATGM.',
    maxSpeed: 10, reverse: 4.5, turnRate: 1.1,
    primary: { kind: 'cannon', name: '120mm', reload: 3.0, speed: 175, dmg: { ground: 115, naval: 70, static: 95, air: 70 }, splash: 4 },
    secondaries: [{ spec: 'atgm', ammo: 5 }],
    counter: { name: 'SMOKE/APS', cd: 4 },
    stats: { Speed: 1, Armor: 5, Firepower: 4, Agility: 2 },
    camDist: 9, camHeight: 3.2,
  },
  destroyer: {
    name: 'Destroyer', short: 'DDG', type: 'ship', model: 'destroyer', hp: 720,
    desc: 'Naval warship. Deck gun, long-range cruise missiles and SAMs. CIWS counters missiles.',
    maxSpeed: 13, reverse: 4, turnRate: 0.32,
    primary: { kind: 'cannon', name: '127mm', reload: 1.2, speed: 210, dmg: { ground: 60, naval: 75, static: 60, air: 40 }, splash: 5 },
    secondaries: [{ spec: 'cruise', ammo: 8 }, { spec: 'sam', ammo: 16 }],
    counter: { name: 'CIWS', cd: 2.6 },
    stats: { Speed: 1, Armor: 5, Firepower: 5, Agility: 1 },
    camDist: 22, camHeight: 7,
  },
  launcher: {
    name: 'Missile Command', short: 'TEL', type: 'ground', model: 'launcher', hp: 180,
    desc: 'Mobile launcher. Fly cruise missiles across the globe yourself and intercept raids.',
    maxSpeed: 8, reverse: 3.5, turnRate: 0.9,
    primary: { kind: 'gun', name: 'MG', rate: 9, speed: 330, dmg: { air: 4, ground: 3, naval: 1, static: 1, missile: 5 }, spread: 0.01, heatPer: 0.01 },
    secondaries: [{ spec: 'cruise', ammo: 6 }, { spec: 'sam', ammo: 10 }],
    counter: { name: 'DECOY', cd: 3.5 },
    stats: { Speed: 1, Armor: 2, Firepower: 5, Agility: 1 },
    camDist: 11, camHeight: 3.6,
  },
};

// Hostile / allied AI unit stats
export const UNITS = {
  fighter: { cat: 'air', hp: 60, radius: 2.2, score: 150, name: 'Fighter', speed: 50, turn: 1.08 },
  ace: { cat: 'air', hp: 120, radius: 2.2, score: 500, name: 'ACE', speed: 56, turn: 1.32 },
  bomber: { cat: 'air', hp: 170, radius: 4.5, score: 250, name: 'Bomber', speed: 28, turn: 0.4 },
  attacker: { cat: 'air', hp: 90, radius: 2.5, score: 200, name: 'Strike plane', speed: 36, turn: 0.8 },
  gunship: { cat: 'air', hp: 75, radius: 2.4, score: 180, name: 'Gunship' },
  tank: { cat: 'ground', hp: 150, radius: 1.8, score: 120, name: 'Tank' },
  apc: { cat: 'ground', hp: 80, radius: 1.6, score: 80, name: 'APC' },
  truck: { cat: 'ground', hp: 60, radius: 1.8, score: 60, name: 'Truck' },
  aa: { cat: 'ground', hp: 90, radius: 2, score: 120, name: 'AA gun' },
  sam: { cat: 'ground', hp: 120, radius: 2.4, score: 200, name: 'SAM site' },
  artillery: { cat: 'ground', hp: 100, radius: 2.2, score: 150, name: 'Artillery' },
  tel: { cat: 'ground', hp: 120, radius: 2.6, score: 220, name: 'Missile launcher' },
  destroyer: { cat: 'naval', hp: 900, radius: 6, score: 600, name: 'Destroyer' },
  patrol: { cat: 'naval', hp: 150, radius: 2.4, score: 150, name: 'Patrol boat' },
  cargo: { cat: 'naval', hp: 500, radius: 6, score: 300, name: 'Cargo ship' },
  radar: { cat: 'static', hp: 300, radius: 4, score: 300, name: 'Radar station' },
  factory: { cat: 'static', hp: 650, radius: 8, score: 400, name: 'Factory' },
  fuel: { cat: 'static', hp: 220, radius: 5, score: 250, name: 'Fuel depot' },
  bunker: { cat: 'static', hp: 500, radius: 4.5, score: 300, name: 'Bunker' },
  hq: { cat: 'static', hp: 900, radius: 7, score: 800, name: 'Command HQ' },
  silo: { cat: 'static', hp: 400, radius: 3.5, score: 400, name: 'Missile silo' },
  outpost: { cat: 'static', hp: 600, radius: 5, score: 0, name: 'Outpost' },
};
